#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Usage: Enc_Power_Shell_Script_Exec [powershell script to execute]"
    exit 1
fi
IP=$( IP_No_Clip );                      
New_IP=$( echo -n $IP );                                                                                                              
Encoded=$( python /home/kali/Ops/Tools/py_encoder.py -s $1 );
echo "powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -enc $Encoded";
echo "powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -NoProfile -enc $Encoded" | clip;
