#!/bin/bash

host=$( hostname -I )
col=$( echo $host | awk '{print NF}')

while [[ $col -ge 1 ]]
do
	result=$( echo $host | awk -F ' ' '{print $'"$col"' }' )
	if [[ $result == *"192.168.119"* ]]; then
		echo $result
		found="yes"
		echo -n $result | clip;
	fi
	((col = col - 1))
done

if [[ $found != "yes" ]]; then
	result=$( echo $host | awk -F ' ' '{print $1}')
	echo $result
	echo -n $result | clip;
fi
