#!/bin/python3
import http.server
import socketserver
import sys

PORT = sys.argv[1]
Handler = http.server.SimpleHTTPRequestHandler

with socketserver.TCPServer(("", int(PORT)), Handler) as httpd:
    print("serving at port", int(PORT))
    httpd.serve_forever()
