#!/bin/bash
IP=$1
BOX=$2

if [ "$#" -ne 2 ]; then
    echo "Usage: recon [IP] [Box Name]. You must enter 2 command line arguments."
    exit
fi

echo "Executing AutoRecon on $IP."
mkdir -p /home/kali/Boxes/$2/AutoRecon
python3 /home/kali/Ops/Tools/AutoRecon/autorecon.py $1 -o /root/Boxes/$2/AutoRecon -vv

