#!/bin/bash
source /root/Ops/Commands/colors.sh
if [ $# -eq 0 ]; then
  echo "Usage:"
  echo "wreverse [reverse port]"
  exit 1
fi

echo -e "${CYAN}Opening reverse shell on port $1.";

rlwrap nc -lvnp $1;
